# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0002_auto_20160828_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='document',
            name='unique_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_viewer.UniqueFile'),
        ),
    ]
