# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0003_auto_20160716_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='coteriedocument',
            name='external_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
