# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161008_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_portrait_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
