# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_external_portrait_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to=home.models.upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_to),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
