# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180706_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.upload_to),
        ),
    ]
