# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180706_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_field',
            field=models.ImageField(upload_to=home.models.image_upload_to),
        ),
    ]
