# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='UserSetting',
        ),
    ]
