# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_viewer', '0001_initial'),
        ('coterie', '0002_auto_20160628_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoterieAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('page_index', models.IntegerField()),
                ('height_percent', models.FloatField()),
                ('width_percent', models.FloatField()),
                ('top_percent', models.FloatField()),
                ('left_percent', models.FloatField()),
                ('frame_color', models.CharField(max_length=18)),
                ('num_like', models.IntegerField(default=0)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoterieAnnotationReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('num_like', models.IntegerField(default=0)),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.CoterieAnnotation')),
                ('reply_to_annotation_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='coterie.CoterieAnnotationReply')),
            ],
        ),
        migrations.CreateModel(
            name='CoterieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('num_like', models.IntegerField(default=0)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoterieDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1028)),
                ('num_visit', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.Coterie')),
                ('unique_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_viewer.UniqueFile')),
            ],
        ),
        migrations.AddField(
            model_name='coteriecomment',
            name='document_this_comment_belongs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.CoterieDocument'),
        ),
        migrations.AddField(
            model_name='coteriecomment',
            name='reply_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='coterie.CoterieComment'),
        ),
        migrations.AddField(
            model_name='coterieannotation',
            name='document_this_annotation_belongs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.CoterieDocument'),
        ),
    ]
