# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0004_coteriedocument_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coteriedocument',
            name='unique_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_viewer.UniqueFile'),
        ),
    ]
