# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coterie', '0005_auto_20180110_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoterieInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_message', models.TextField(blank=True)),
                ('send_datetime', models.DateTimeField(auto_now_add=True)),
                ('acceptance', models.BooleanField()),
                ('response_datetime', models.DateTimeField(auto_now=True)),
                ('coterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.Coterie')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitation_set', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitation_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
