# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0007_auto_20180606_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coterieinvitation',
            name='acceptance',
            field=models.NullBooleanField(),
        ),
    ]
