# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0008_auto_20180606_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='coterieannotation',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coterieannotationreply',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coteriecomment',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
