# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coterie', '0009_auto_20180617_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoterieApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_message', models.TextField(blank=True)),
                ('send_datetime', models.DateTimeField(auto_now_add=True)),
                ('acceptance', models.NullBooleanField()),
                ('response_datetime', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_set', to='coterie.Coterie')),
            ],
        ),
    ]
