# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0010_coterieapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coterie',
            name='applicants',
        ),
        migrations.AlterField(
            model_name='coterieapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_application_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
