# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0011_auto_20180620_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coterieannotationreply',
            name='reply_to_annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotationreply_set', to='coterie.CoterieAnnotation'),
        ),
    ]
