# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0014_auto_20180703_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coterieapplication',
            name='acceptance',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coterieinvitation',
            name='acceptance',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
