# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0016_coteriedocument_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coterieannotation',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
