# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coterie', '0020_coteriedocument_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='coteriedocument',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_coteriedocument_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
