# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coterie', '0021_coteriedocument_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonRegisteredUserTempCoterieInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invitee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invitation_message', models.TextField(blank=True)),
                ('send_datetime', models.DateTimeField(auto_now_add=True)),
                ('coterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.Coterie')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nonregisteredusertempinvitation_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
