# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0023_auto_20181103_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64)),
                ('coterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coterie.Coterie')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_code', to='coterie.CoterieInvitation')),
                ('nonregistered_user_temp_invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_code', to='coterie.NonRegisteredUserTempCoterieInvitation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
