# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0025_invitationcode_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcode',
            name='receiver',
        ),
    ]
