# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coterie', '0026_remove_invitationcode_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoterieReadlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=1028)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('collectors', models.ManyToManyField(blank=True, related_name='collected_coteriereadlist_set', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_coteriereadlist_set', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='belonged_coteriereadlist_set', to='coterie.CoterieDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
