# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coterie', '0027_coteriereadlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coteriereadlist',
            name='coterie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coteriereadlist_set', to='coterie.Coterie'),
            preserve_default=False,
        ),
    ]
