from fcm_django.models import FCMDevice
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.views.generic import View
import json

from ..models import User

import logging, logging.config
import sys

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO'
    }
}

logging.config.dictConfig(LOGGING)

# handles the deletion of rows in the table generated by django-fcm
def delete_device(request):
  # TODO: ensure request user is the owner of that device
  # TODO: handle error cases
  logging.info(request.user) # why I get AnonymousUser here?
  registration_id = json.loads(request.body)['token_id']
  devices = FCMDevice.objects.filter(registration_id=registration_id).all()
  for device in devices:
    # TODO: check that device.user == request.user, then delete
    logging.info(device.user)
    device.delete()
  return HttpResponse(status=200)
