# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='frame_color',
            field=models.CharField(max_length=32),
        ),
    ]
