# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0004_auto_20180617_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='annotationreply',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='annotationreply',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
