# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0006_auto_20180703_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=1028),
        ),
    ]
