# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0007_auto_20180703_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='external_url',
            field=models.CharField(blank=True, db_index=True, max_length=2083),
        ),
    ]
