# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180706_2257'),
        ('file_viewer', '0009_document_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1028)),
                ('open_url', models.CharField(db_index=True, max_length=1028)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='num_visit',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='documentthumbnail',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_viewer.Document'),
        ),
        migrations.AddField(
            model_name='documentthumbnail',
            name='thumbnail_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UploadedImage'),
        ),
    ]
