# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0013_auto_20180710_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
