# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0014_annotation_edit_time'),
        ('file_viewer', '0014_documentthumbnail_create_time'),
    ]

    operations = [
    ]
