# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0014_annotation_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
