# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0015_merge_20180712_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationreply',
            name='edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
