# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_viewer', '0016_annotationreply_edit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=1028)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('collectors', models.ManyToManyField(blank=True, related_name='collected_readlist_set', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_readlist_set', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='belonged_readlist_set', to='file_viewer.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
