# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0017_readlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
