# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0018_readlist_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
