# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0019_readlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
