# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_viewer', '0020_auto_20180810_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentthumbnail',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_set', to='file_viewer.Document'),
        ),
    ]
